# Generated by Django 5.0.2 on 2024-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
            ],
            options={
                'db_table': 'temp_status',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, default='user', max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('branch', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'useraccount',
            },
        ),
    ]
