# Generated by Django 5.0.2 on 2024-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstatus',
            name='status',
            field=models.CharField(choices=[('O', 'Online'), ('F', 'Offline')], max_length=1),
        ),
    ]
