# Generated by Django 5.0.2 on 2024-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tempstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstatus',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50),
        ),
    ]
